2020-05-06T22:54:34.7608736+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-05-06T22:54:34.7742077+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-06T22:54:34.7768314+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-06T22:54:34.7799331+03:00  [INF] Content root path: "C:\xampp\htdocs\school\school.API" (b5d60022)
2020-05-06T22:54:36.3443832+03:00 0HLVHUT6OIQSV:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T22:54:36.3597985+03:00 0HLVHUT6OIQSV:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T22:55:18.6094455+03:00 0HLVHUT6OIQT0:00000002 [ERR] An exception occurred while iterating over the results of a query for context type '"school.DATA.dataContext"'."
""System.InvalidOperationException: Invalid attempt to call CheckDataIsReady when reader is closed.
   at Microsoft.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()" (f5c7ac34)
System.InvalidOperationException: Invalid attempt to call CheckDataIsReady when reader is closed.
   at Microsoft.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.ReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at Microsoft.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2020-05-06T23:04:29.9320659+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-05-06T23:04:29.9479164+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-06T23:04:29.9514703+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-06T23:04:29.9546782+03:00  [INF] Content root path: "C:\xampp\htdocs\school\school.API" (b5d60022)
2020-05-06T23:04:30.6398049+03:00 0HLVHV2NVJHF9:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T23:04:30.6794795+03:00 0HLVHV2NVJHF9:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T23:06:38.4857287+03:00 0HLVHV2NVJHFC:00000002 [ERR] An exception occurred while iterating over the results of a query for context type '"school.DATA.dataContext"'."
""System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()" (f5c7ac34)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
2020-05-06T23:06:43.3066644+03:00 0HLVHV2NVJHFC:00000002 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at school.REPOSITORY.CourseRepository.updateCoursePhoto(Int32 courseId, String dbPath) in C:\xampp\htdocs\school\school.REPOSITORY\CourseRepository.cs:line 39
   at school.API.Controllers.CourseController.UploadPhoto() in C:\xampp\htdocs\school\school.API\Controllers\CourseController.cs:line 141
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-05-06T23:06:43.4503147+03:00 0HLVHV2NVJHFC:00000002 [ERR] An error occurred using a transaction. (2ffd8ddb)
2020-05-06T23:09:16.0189625+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-05-06T23:09:16.0441926+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-05-06T23:09:16.0523320+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-05-06T23:09:16.0642008+03:00  [INF] Content root path: "C:\xampp\htdocs\school\school.API" (b5d60022)
2020-05-06T23:09:16.5546246+03:00 0HLVHV5D7KAEE:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T23:09:16.5698128+03:00 0HLVHV5D7KAEE:00000001 [WRN] Failed to determine the https port for redirect. (ca76cc21)
2020-05-06T23:09:59.9964329+03:00 0HLVHV5D7KAEF:00000004 [INF] Hello, course uptaded! (98d02b1e)
